//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v2.0.5.6
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace JobApp.Models.JobModel
{
   /// <summary>
   /// Job masterclass
   /// </summary>
   public class Job
   {
      //partial void Init();

      ///// <summary>
      ///// Default constructor. Protected due to required properties, but present because EF needs it.
      ///// </summary>
      //protected Job()
      //{
      //   JobData = new System.Collections.Generic.HashSet<global::JobApp.Models.JobModel.JobData>();
      //   JobSkillz = new System.Collections.Generic.HashSet<global::JobApp.Models.JobModel.JobSkill>();

      //   Init();
      //}

      ///// <summary>
      ///// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      ///// </summary>
      //public static Job CreateJobUnsafe()
      //{
      //   return new Job();
      //}

      ///// <summary>
      ///// Public constructor with required data
      ///// </summary>
      ///// <param name="title">Required, Max length = 50</param>
      ///// <param name="_joboffer0"></param>
      //public Job(string title, global::JobApp.Models.JobModel.JobOffer _joboffer0)
      //{
      //   if (string.IsNullOrEmpty(title)) throw new ArgumentNullException(nameof(title));
      //   this.Title = title;

      //   if (_joboffer0 == null) throw new ArgumentNullException(nameof(_joboffer0));
      //   _joboffer0.Job = this;

      //   this.JobData = new System.Collections.Generic.HashSet<global::JobApp.Models.JobModel.JobData>();
      //   this.JobSkillz = new System.Collections.Generic.HashSet<global::JobApp.Models.JobModel.JobSkill>();

      //   Init();
      //}

      ///// <summary>
      ///// Static create function (for use in LINQ queries, etc.)
      ///// </summary>
      ///// <param name="title">Required, Max length = 50</param>
      ///// <param name="_joboffer0"></param>
      //public static Job Create(string title, global::JobApp.Models.JobModel.JobOffer _joboffer0)
      //{
      //   return new Job(title, _joboffer0);
      //}

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// Identity, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get;  set; }

      /// <summary>
      /// FK to an offered job
      /// </summary>
      public int? JobOfferId { get; set; }

      /// <summary>
      /// Required, Max length = 50
      /// Required, Max length = 50
      /// </summary>
      [Required]
      [MaxLength(50)]
      [StringLength(50)]
      public string Title { get; set; }

      /// <summary>
      /// Max length = 30
      /// Max length = 30
      /// </summary>
      [MaxLength(30)]
      [StringLength(30)]
      public string TitleAlt { get; set; }

      /// <summary>
      /// Max length = 50
      /// Required, Max length = 50
      /// </summary>
      [MaxLength(50)]
      [StringLength(50)]
      public string TitleAlt2 { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/

      /// <summary>
      /// summary
      /// </summary>
      public virtual ICollection<global::JobApp.Models.JobModel.JobData> JobData { get; protected set; }

        /// <summary>
        /// job deletes associated skills
        /// </summary>
        public virtual ICollection<global::JobApp.Models.JobModel.JobSkill> JobSkillz { get; protected set; }
        public virtual ICollection<global::JobApp.Models.JobModel.JobOffer> Offers { get; protected set; }

    }
}

