//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v2.0.5.6
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace JobApp.Models.JobModel
{
   /// <summary>
   /// Data about a Jobexchange
   /// </summary>
   public class JobExchange
   {
      //partial void Init();

      ///// <summary>
      ///// Default constructor. Protected due to required properties, but present because EF needs it.
      ///// </summary>
      //protected JobExchange()
      //{
      //   Init();
      //}

      ///// <summary>
      ///// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      ///// </summary>
      //public static JobExchange CreateJobExchangeUnsafe()
      //{
      //   return new JobExchange();
      //}

      ///// <summary>
      ///// Public constructor with required data
      ///// </summary>
      ///// <param name="name">Required, Min length = 3, Max length = 30</param>
      ///// <param name="current">Historic retention property</param>
      ///// <param name="_joboffer0"></param>
      //public JobExchange(string name, bool current, global::JobApp.Models.JobModel.JobOffer _joboffer0)
      //{
      //   if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
      //   this.Name = name;

      //   this.Current = current;

      //   if (_joboffer0 == null) throw new ArgumentNullException(nameof(_joboffer0));
      //   _joboffer0.JobExchange = this;


      //   Init();
      //}

      ///// <summary>
      ///// Static create function (for use in LINQ queries, etc.)
      ///// </summary>
      ///// <param name="name">Required, Min length = 3, Max length = 30</param>
      ///// <param name="current">Historic retention property</param>
      ///// <param name="_joboffer0"></param>
      //public static JobExchange Create(string name, bool current, global::JobApp.Models.JobModel.JobOffer _joboffer0)
      //{
      //   return new JobExchange(name, current, _joboffer0);
      //}

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// Identity, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get; protected set; }

      /// <summary>
      /// Required, Min length = 3, Max length = 30
      /// Required, Min length = 3, Max length = 30
      /// </summary>
      [Required]
      [MinLength(3)]
      [MaxLength(30)]
      [StringLength(30)]
      public string Name { get; set; }

      /// <summary>
      /// Max length = 50
      /// Required, Max length = 50
      /// </summary>
      [MaxLength(50)]
      [StringLength(50)]
      public string Url { get; set; }

      /// <summary>
      /// Required
      /// Historic retention property
      /// </summary>
      [Required]
      public bool Current { get; set; }

        /*************************************************************************
         * Navigation properties
         *************************************************************************/
        public virtual ICollection<global::JobApp.Models.JobModel.JobOffer> Offers { get; protected set; }

    }
}

