//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v2.0.5.6
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace JobApp.Models.CompanyModel
{
   /// <summary>
   /// The companies important dates
   /// </summary>
   public class CompanyHistory
   {
      //partial void Init();

      ///// <summary>
      ///// Default constructor. Protected due to required properties, but present because EF needs it.
      ///// </summary>
      //protected CompanyHistory()
      //{
      //   Init();
      //}

      ///// <summary>
      ///// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      ///// </summary>
      //public static CompanyHistory CreateCompanyHistoryUnsafe()
      //{
      //   return new CompanyHistory();
      //}

      ///// <summary>
      ///// Public constructor with required data
      ///// </summary>
      ///// <param name="companyid">Required</param>
      ///// <param name="name">Max length = 50</param>
      ///// <param name="date">Required</param>
      ///// <param name="_company0"></param>
      //public CompanyHistory(int companyid, string name, DateTime date, global::JobApp.Models.CompanyModel.Company _company0)
      //{
      //   this.CompanyId = companyid;

      //   if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
      //   this.Name = name;

      //   this.Date = date;

      //   if (_company0 == null) throw new ArgumentNullException(nameof(_company0));
      //   _company0.HistoryList.Add(this);


      //   Init();
      //}

      ///// <summary>
      ///// Static create function (for use in LINQ queries, etc.)
      ///// </summary>
      ///// <param name="companyid">Required</param>
      ///// <param name="name">Max length = 50</param>
      ///// <param name="date">Required</param>
      ///// <param name="_company0"></param>
      //public static CompanyHistory Create(int companyid, string name, DateTime date, global::JobApp.Models.CompanyModel.Company _company0)
      //{
      //   return new CompanyHistory(companyid, name, date, _company0);
      //}

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// Identity, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get; protected set; }

      /// <summary>
      /// Required
      /// Required
      /// </summary>
      [Required]
      public int CompanyId { get; set; }

      /// <summary>
      /// Required, Max length = 50
      /// Max length = 50
      /// </summary>
      [Required]
      [MaxLength(50)]
      [StringLength(50)]
      public string Name { get; set; }

      /// <summary>
      /// Max length = 250
      /// Max length = 50
      /// </summary>
      [MaxLength(250)]
      [StringLength(250)]
      public string Content { get; set; }

      /// <summary>
      /// Required
      /// Required
      /// </summary>
      [Required]
      public DateTime Date { get; set; }

        /*************************************************************************
         * Navigation properties
         *************************************************************************/
        public Company Company { get; set; }

    }
}

