//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v2.0.5.6
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace JobApp.Models.CompanyModel
{
  /// <summary>
  /// Company masterclass
  /// </summary>
  public class Company
  {
    
    /*************************************************************************
     * Properties
     *************************************************************************/

    /// <summary>
    /// Identity, Required
    /// Identity, Required
    /// </summary>
    [Key]
    [Required]
    public int Id { get; internal set; }

    /// <summary>
    /// Required, Max length = 50
    /// Required, Max length = 50
    /// </summary>
    [Required]
    [MaxLength(50)]
    [StringLength(50)]
    public string CompanyName { get; set; }

    /// <summary>
    /// Required
    /// Historic retention property
    /// </summary>
    [Required]
    public bool Current { get; set; }
    // public byte[] LogoBig { get; set; }

    [Required]
    [MaxLength(250)]
    [StringLength(250)]
    public string Description { get; set; }



    /*************************************************************************
     * Navigation properties
     *************************************************************************/

    /// <summary>
    /// company deletes branches
    /// </summary>
    public virtual ICollection<global::JobApp.Models.CompanyModel.CompanyBranch> Branches { get; protected set; }

    /// <summary>
    /// summary
    /// </summary>
    public virtual ICollection<global::JobApp.Models.CompanyModel.CompanyHistory> HistoryList { get; protected set; }


  }
}

