//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v2.0.5.6
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace JobApp.Models.ApplicationModel
{
   /// <summary>
   /// Header of an application
   /// </summary>
   public class ApplicationHeader
   {
      //partial void Init();

      ///// <summary>
      ///// Default constructor. Protected due to required properties, but present because EF needs it.
      ///// </summary>
      //protected ApplicationHeader()
      //{
      //   Init();
      //}

      ///// <summary>
      ///// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      ///// </summary>
      //public static ApplicationHeader CreateApplicationHeaderUnsafe()
      //{
      //   return new ApplicationHeader();
      //}

      ///// <summary>
      ///// Public constructor with required data
      ///// </summary>
      ///// <param name="applicationnid">Required</param>
      ///// <param name="title">Required, Max length = 20</param>
      ///// <param name="content">Required, Max length = 1500</param>
      ///// <param name="_application0"></param>
      //public ApplicationHeader(int applicationnid, string title, string content, global::JobApp.Models.ApplicationModel.Application _application0)
      //{
      //   this.ApplicationnId = applicationnid;

      //   if (string.IsNullOrEmpty(title)) throw new ArgumentNullException(nameof(title));
      //   this.Title = title;

      //   if (string.IsNullOrEmpty(content)) throw new ArgumentNullException(nameof(content));
      //   this.Content = content;

      //   if (_application0 == null) throw new ArgumentNullException(nameof(_application0));
      //   _application0.Header = this;


      //   Init();
      //}

      ///// <summary>
      ///// Static create function (for use in LINQ queries, etc.)
      ///// </summary>
      ///// <param name="applicationnid">Required</param>
      ///// <param name="title">Required, Max length = 20</param>
      ///// <param name="content">Required, Max length = 1500</param>
      ///// <param name="_application0"></param>
      //public static ApplicationHeader Create(int applicationnid, string title, string content, global::JobApp.Models.ApplicationModel.Application _application0)
      //{
      //   return new ApplicationHeader(applicationnid, title, content, _application0);
      //}

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// Identity, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get; protected set; }

      /// <summary>
      /// Required
      /// Required
      /// </summary>
      [Required]
      public int ApplicationnId { get; set; }

      /// <summary>
      /// Required, Max length = 20
      /// Required, Max length = 20
      /// </summary>
      [Required]
      [MaxLength(20)]
      [StringLength(20)]
      public string Title { get; set; }

      /// <summary>
      /// Required, Max length = 1500
      /// Required, Max length = 1500
      /// </summary>
      [Required]
      [MaxLength(1500)]
      [StringLength(1500)]
      public string Content { get; set; }

      /*************************************************************************
       * Navigation properties
       *************************************************************************/
      public List<Application> Applications { get; set; }
   }
}

