//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v2.0.5.6
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace JobApp.Models.UserModel
{
   /// <summary>
   /// description of a particular skill the user has
   /// </summary>
   public class UserSkill
   {
      //partial void Init();

      ///// <summary>
      ///// Default constructor. Protected due to required properties, but present because EF needs it.
      ///// </summary>
      //protected UserSkill()
      //{
      //   Init();
      //}

      ///// <summary>
      ///// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      ///// </summary>
      //public static UserSkill CreateUserSkillUnsafe()
      //{
      //   return new UserSkill();
      //}

      ///// <summary>
      ///// Public constructor with required data
      ///// </summary>
      ///// <param name="userid">Required</param>
      ///// <param name="skillname">Required, Max length = 30</param>
      ///// <param name="skilldescritpion">Required, Max length = 100</param>
      ///// <param name="selfrating">Required</param>
      ///// <param name="current">Historic retention property</param>
      ///// <param name="_user0"></param>
      //public UserSkill(int userid, string skillname, string skilldescritpion, int selfrating, bool current, global::JobApp.Models.UserModel.User _user0)
      //{
      //   this.UserId = userid;

      //   if (string.IsNullOrEmpty(skillname)) throw new ArgumentNullException(nameof(skillname));
      //   this.SkillName = skillname;

      //   if (string.IsNullOrEmpty(skilldescritpion)) throw new ArgumentNullException(nameof(skilldescritpion));
      //   this.SkillDescritpion = skilldescritpion;

      //   this.SelfRating = selfrating;

      //   this.Current = current;

      //   if (_user0 == null) throw new ArgumentNullException(nameof(_user0));
      //   _user0.Skills.Add(this);


      //   Init();
      //}

      ///// <summary>
      ///// Static create function (for use in LINQ queries, etc.)
      ///// </summary>
      ///// <param name="userid">Required</param>
      ///// <param name="skillname">Required, Max length = 30</param>
      ///// <param name="skilldescritpion">Required, Max length = 100</param>
      ///// <param name="selfrating">Required</param>
      ///// <param name="current">Historic retention property</param>
      ///// <param name="_user0"></param>
      //public static UserSkill Create(int userid, string skillname, string skilldescritpion, int selfrating, bool current, global::JobApp.Models.UserModel.User _user0)
      //{
      //   return new UserSkill(userid, skillname, skilldescritpion, selfrating, current, _user0);
      //}

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// Identity, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get; protected set; }

      /// <summary>
      /// Required
      /// Required
      /// </summary>
      [Required]
      public int UserId { get; set; }

      /// <summary>
      /// Required, Max length = 30
      /// Required, Max length = 30
      /// </summary>
      [Required]
      [MaxLength(30)]
      [StringLength(30)]
      public string SkillName { get; set; }

      /// <summary>
      /// Required, Max length = 100
      /// Required, Max length = 100
      /// </summary>
      [Required]
      [MaxLength(100)]
      [StringLength(100)]
      public string SkillDescritpion { get; set; }

      /// <summary>
      /// Required
      /// Required
      /// </summary>
      [Required]
      public int SelfRating { get; set; }

      /// <summary>
      /// Required
      /// Historic retention property
      /// </summary>
      [Required]
      public bool Current { get; set; }

        /*************************************************************************
         * Navigation properties
         *************************************************************************/
        public User User { get; set; }

    }
}

