//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
//
//     Produced by Entity Framework Visual Editor v2.0.5.6
//     Source:                    https://github.com/msawczyn/EFDesigner
//     Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=michaelsawczyn.EFDesigner
//     Documentation:             https://msawczyn.github.io/EFDesigner/
//     License (MIT):             https://github.com/msawczyn/EFDesigner/blob/master/LICENSE
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Runtime.CompilerServices;

namespace JobApp.Models.UserModel
{
   /// <summary>
   /// Name and URL of the users websites
   /// </summary>
   public class UserWebsite
   {
      //partial void Init();

      ///// <summary>
      ///// Default constructor. Protected due to required properties, but present because EF needs it.
      ///// </summary>
      //protected UserWebsite()
      //{
      //   Init();
      //}

      ///// <summary>
      ///// Replaces default constructor, since it's protected. Caller assumes responsibility for setting all required values before saving.
      ///// </summary>
      //public static UserWebsite CreateUserWebsiteUnsafe()
      //{
      //   return new UserWebsite();
      //}

      ///// <summary>
      ///// Public constructor with required data
      ///// </summary>
      ///// <param name="userid">Required</param>
      ///// <param name="name">Required, Max length = 30</param>
      ///// <param name="url">Required, Max length = 50</param>
      ///// <param name="_user0"></param>
      //public UserWebsite(int userid, string name, string url, global::JobApp.Models.UserModel.User _user0)
      //{
      //   this.UserId = userid;

      //   if (string.IsNullOrEmpty(name)) throw new ArgumentNullException(nameof(name));
      //   this.Name = name;

      //   if (string.IsNullOrEmpty(url)) throw new ArgumentNullException(nameof(url));
      //   this.Url = url;

      //   if (_user0 == null) throw new ArgumentNullException(nameof(_user0));
      //   _user0.Websites.Add(this);


      //   Init();
      //}

      ///// <summary>
      ///// Static create function (for use in LINQ queries, etc.)
      ///// </summary>
      ///// <param name="userid">Required</param>
      ///// <param name="name">Required, Max length = 30</param>
      ///// <param name="url">Required, Max length = 50</param>
      ///// <param name="_user0"></param>
      //public static UserWebsite Create(int userid, string name, string url, global::JobApp.Models.UserModel.User _user0)
      //{
      //   return new UserWebsite(userid, name, url, _user0);
      //}

      /*************************************************************************
       * Properties
       *************************************************************************/

      /// <summary>
      /// Identity, Required
      /// Identity, Required
      /// </summary>
      [Key]
      [Required]
      public int Id { get; protected set; }

      /// <summary>
      /// Required
      /// Required
      /// </summary>
      [Required]
      public int UserId { get; set; }

      /// <summary>
      /// Required, Max length = 30
      /// Required, Max length = 30
      /// </summary>
      [Required]
      [MaxLength(30)]
      [StringLength(30)]
      public string Name { get; set; }

      /// <summary>
      /// Max length = 150
      /// Max length = 150
      /// </summary>
      [MaxLength(150)]
      [StringLength(150)]
      public string Content { get; set; }

      /// <summary>
      /// Required, Max length = 50
      /// Required, Max length = 50
      /// </summary>
      [Required]
      [MaxLength(50)]
      [StringLength(50)]
      public string Url { get; set; }

        /*************************************************************************
         * Navigation properties
         *************************************************************************/
        public User User { get; set; }

    }
}

