// <auto-generated />
using System;
using JobApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JobApp.Migrations.JobDb
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20201126143542_JobFKremove")]
    partial class JobFKremove
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JobApp.Models.ALVModel.Jobsuche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAnswered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("JobOffer.Jobsuche_Id")
                        .HasColumnType("int");

                    b.Property<int>("JobOfferId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Proof")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<int>("User.JobsGesucht_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobOffer.Jobsuche_Id")
                        .IsUnique();

                    b.HasIndex("User.JobsGesucht_Id");

                    b.ToTable("Jobsuche");
                });

            modelBuilder.Entity("JobApp.Models.ApplicationModel.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<byte[]>("Current")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("DateAnswered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSent")
                        .HasColumnType("datetime2");

                    b.Property<int?>("JobOffer.Application_Id")
                        .HasColumnType("int");

                    b.Property<int?>("JobOfferId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("User.Applications_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobOffer.Application_Id")
                        .IsUnique()
                        .HasFilter("[JobOffer.Application_Id] IS NOT NULL");

                    b.HasIndex("User.Applications_Id");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("JobApp.Models.ApplicationModel.ApplicationBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Application.Body_Id")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationnId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Application.Body_Id")
                        .IsUnique()
                        .HasFilter("[Application.Body_Id] IS NOT NULL");

                    b.ToTable("ApplicationBody");
                });

            modelBuilder.Entity("JobApp.Models.ApplicationModel.ApplicationFooter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Application.Footer_Id")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationnId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Application.Footer_Id")
                        .IsUnique()
                        .HasFilter("[Application.Footer_Id] IS NOT NULL");

                    b.ToTable("ApplicationFooter");
                });

            modelBuilder.Entity("JobApp.Models.ApplicationModel.ApplicationHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Application.Header_Id")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationnId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("Application.Header_Id")
                        .IsUnique()
                        .HasFilter("[Application.Header_Id] IS NOT NULL");

                    b.ToTable("ApplicationHeader");
                });

            modelBuilder.Entity("JobApp.Models.CompanyModel.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Current")
                        .HasColumnType("bit");

                    b.Property<int?>("JobOffer.Company_Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("LogoBig")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobOffer.Company_Id")
                        .IsUnique()
                        .HasFilter("[JobOffer.Company_Id] IS NOT NULL");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("JobApp.Models.CompanyModel.CompanyBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AddressNation")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AddressState")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Company.Branches_Id")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Company.Branches_Id");

                    b.ToTable("CompanyBranch");
                });

            modelBuilder.Entity("JobApp.Models.CompanyModel.CompanyContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompanyBranch.Contacts_Id")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyBranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EmailAddressAlt")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("PhoneNumberAlt")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CompanyBranch.Contacts_Id");

                    b.ToTable("CompanyContactData");
                });

            modelBuilder.Entity("JobApp.Models.CompanyModel.CompanyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Company.HistoryList_Id")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Company.HistoryList_Id");

                    b.ToTable("CompanyHistory");
                });

            modelBuilder.Entity("JobApp.Models.HeadHunterModel.HeadHunter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JobOffer.HeadHunter_Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("JobOffer.HeadHunter_Id")
                        .IsUnique()
                        .HasFilter("[JobOffer.HeadHunter_Id] IS NOT NULL");

                    b.ToTable("Headhunter");
                });

            modelBuilder.Entity("JobApp.Models.HeadHunterModel.HeadHunterContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressCity")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AddressNation")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AddressState")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AddressStreet")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int?>("HeadHunter.Name_Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JobExchangeId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumberAlt")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("HeadHunter.Name_Id");

                    b.ToTable("HeadhuntercontactData");
                });

            modelBuilder.Entity("JobApp.Models.JobModel.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("JobOffer.Job_Id")
                        .HasColumnType("int");

                    b.Property<int?>("JobOfferId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("TitleAlt")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("TitleAlt2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("JobOffer.Job_Id")
                        .IsUnique()
                        .HasFilter("[JobOffer.Job_Id] IS NOT NULL");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("JobApp.Models.JobModel.JobData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Current")
                        .HasColumnType("bit");

                    b.Property<string>("DescriptionLong")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Job.JobData_Id")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxSalary")
                        .HasColumnType("decimal(5,3)");

                    b.Property<decimal>("MinSalary")
                        .HasColumnType("decimal(5,3)");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Job.JobData_Id");

                    b.ToTable("JobData");
                });

            modelBuilder.Entity("JobApp.Models.JobModel.JobExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Current")
                        .HasColumnType("bit");

                    b.Property<int?>("JobOffer.JobExchange_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("JobOffer.JobExchange_Id")
                        .IsUnique()
                        .HasFilter("[JobOffer.JobExchange_Id] IS NOT NULL");

                    b.ToTable("JobExchange");
                });

            modelBuilder.Entity("JobApp.Models.JobModel.JobOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicationnId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyBranchId")
                        .HasColumnType("int");

                    b.Property<int?>("HeadHunterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JobExchangeId")
                        .HasColumnType("int");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("JobOfferUrl")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Releasedate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SalaryOffered")
                        .HasColumnType("decimal(5,3)");

                    b.HasKey("Id");

                    b.ToTable("JobOffer");
                });

            modelBuilder.Entity("JobApp.Models.JobModel.JobSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int>("Job.JobSkillz_Id")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("Job.JobSkillz_Id");

                    b.ToTable("JobSkill");
                });

            modelBuilder.Entity("JobApp.Models.UserModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nationality2")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PictureAlt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Religion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserContactData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AddressNation")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AddressState")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("Current")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("EmailAddressAlt")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("PhoneNumberAlt")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("User.ContactData_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User.ContactData_Id")
                        .IsUnique();

                    b.ToTable("UserContactData");
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressNation")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Facility")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FacilityAddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FacilityAddressState")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FacilityAddressStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Graduation")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestimonyUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("User.EducationHistory_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User.EducationHistory_Id");

                    b.ToTable("UserEducation");
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserJobHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Current")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(5,3)");

                    b.Property<string>("SkillSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestimonyUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("User.JobHistory_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User.JobHistory_Id");

                    b.ToTable("UserJobHistory");
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Current")
                        .HasColumnType("bit");

                    b.Property<int>("SelfRating")
                        .HasColumnType("int");

                    b.Property<string>("SkillDescritpion")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("User.Skills_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User.Skills_Id");

                    b.ToTable("UserSkill");
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserWebsite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("User.Websites_Id")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("User.Websites_Id");

                    b.ToTable("UserWebsite");
                });

            modelBuilder.Entity("JobApp.Models.ALVModel.Jobsuche", b =>
                {
                    b.HasOne("JobApp.Models.JobModel.JobOffer", null)
                        .WithOne("Jobsuche")
                        .HasForeignKey("JobApp.Models.ALVModel.Jobsuche", "JobOffer.Jobsuche_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobApp.Models.UserModel.User", null)
                        .WithMany("JobsGesucht")
                        .HasForeignKey("User.JobsGesucht_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.ApplicationModel.Application", b =>
                {
                    b.HasOne("JobApp.Models.JobModel.JobOffer", null)
                        .WithOne("Application")
                        .HasForeignKey("JobApp.Models.ApplicationModel.Application", "JobOffer.Application_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JobApp.Models.UserModel.User", null)
                        .WithMany("Applications")
                        .HasForeignKey("User.Applications_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.ApplicationModel.ApplicationBody", b =>
                {
                    b.HasOne("JobApp.Models.ApplicationModel.Application", null)
                        .WithOne("Body")
                        .HasForeignKey("JobApp.Models.ApplicationModel.ApplicationBody", "Application.Body_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JobApp.Models.ApplicationModel.ApplicationFooter", b =>
                {
                    b.HasOne("JobApp.Models.ApplicationModel.Application", null)
                        .WithOne("Footer")
                        .HasForeignKey("JobApp.Models.ApplicationModel.ApplicationFooter", "Application.Footer_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JobApp.Models.ApplicationModel.ApplicationHeader", b =>
                {
                    b.HasOne("JobApp.Models.ApplicationModel.Application", null)
                        .WithOne("Header")
                        .HasForeignKey("JobApp.Models.ApplicationModel.ApplicationHeader", "Application.Header_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JobApp.Models.CompanyModel.Company", b =>
                {
                    b.HasOne("JobApp.Models.JobModel.JobOffer", null)
                        .WithOne("Company")
                        .HasForeignKey("JobApp.Models.CompanyModel.Company", "JobOffer.Company_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JobApp.Models.CompanyModel.CompanyBranch", b =>
                {
                    b.HasOne("JobApp.Models.CompanyModel.Company", null)
                        .WithMany("Branches")
                        .HasForeignKey("Company.Branches_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.CompanyModel.CompanyContactData", b =>
                {
                    b.HasOne("JobApp.Models.CompanyModel.CompanyBranch", null)
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyBranch.Contacts_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobApp.Models.CompanyModel.CompanyHistory", b =>
                {
                    b.HasOne("JobApp.Models.CompanyModel.Company", null)
                        .WithMany("HistoryList")
                        .HasForeignKey("Company.HistoryList_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.HeadHunterModel.HeadHunter", b =>
                {
                    b.HasOne("JobApp.Models.JobModel.JobOffer", null)
                        .WithOne("HeadHunter")
                        .HasForeignKey("JobApp.Models.HeadHunterModel.HeadHunter", "JobOffer.HeadHunter_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JobApp.Models.HeadHunterModel.HeadHunterContactData", b =>
                {
                    b.HasOne("JobApp.Models.HeadHunterModel.HeadHunter", null)
                        .WithMany("Name")
                        .HasForeignKey("HeadHunter.Name_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("JobApp.Models.JobModel.Job", b =>
                {
                    b.HasOne("JobApp.Models.JobModel.JobOffer", null)
                        .WithOne("Job")
                        .HasForeignKey("JobApp.Models.JobModel.Job", "JobOffer.Job_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JobApp.Models.JobModel.JobData", b =>
                {
                    b.HasOne("JobApp.Models.JobModel.Job", null)
                        .WithMany("JobData")
                        .HasForeignKey("Job.JobData_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.JobModel.JobExchange", b =>
                {
                    b.HasOne("JobApp.Models.JobModel.JobOffer", null)
                        .WithOne("JobExchange")
                        .HasForeignKey("JobApp.Models.JobModel.JobExchange", "JobOffer.JobExchange_Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("JobApp.Models.JobModel.JobSkill", b =>
                {
                    b.HasOne("JobApp.Models.JobModel.Job", null)
                        .WithMany("JobSkillz")
                        .HasForeignKey("Job.JobSkillz_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserContactData", b =>
                {
                    b.HasOne("JobApp.Models.UserModel.User", null)
                        .WithOne("ContactData")
                        .HasForeignKey("JobApp.Models.UserModel.UserContactData", "User.ContactData_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserEducation", b =>
                {
                    b.HasOne("JobApp.Models.UserModel.User", null)
                        .WithMany("EducationHistory")
                        .HasForeignKey("User.EducationHistory_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserJobHistory", b =>
                {
                    b.HasOne("JobApp.Models.UserModel.User", null)
                        .WithMany("JobHistory")
                        .HasForeignKey("User.JobHistory_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserSkill", b =>
                {
                    b.HasOne("JobApp.Models.UserModel.User", null)
                        .WithMany("Skills")
                        .HasForeignKey("User.Skills_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApp.Models.UserModel.UserWebsite", b =>
                {
                    b.HasOne("JobApp.Models.UserModel.User", null)
                        .WithMany("Websites")
                        .HasForeignKey("User.Websites_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
